export * from './IconAngular'
export * from './IconAstro'
export * from './IconJs'
export * from './IconNext'
export * from './IconPython'
export * from './IconReact'
export * from './IconTailwild'
export * from './IconVue'
